name: Build Keycloak Image

on:
  push:
    branches: ["main"]
    paths:
      - "keycloak/**"
      - ".trivyignore"
      - ".github/workflows/keycloak-build.yml"
  pull_request:
    paths:
      - "keycloak/**"
      - ".trivyignore"
      - ".github/workflows/keycloak-build.yml"

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build:
    uses: zavestudios/platform-pipelines/.github/workflows/container-build.yml@c0aa80bb405fa24ede5ebcf1c40b0be90328386c
    with:
      image_name: zavestudios/keycloak
      context: .
      dockerfile: keycloak/Dockerfile
      push: ${{ github.event_name != 'pull_request' }}
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
